name: Publish yarndoc

on:
  workflow_dispatch:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: Setup Ruby using Bundler
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0'

      - name: install gems
        run: bundle install && gem install yard

      - name: generate documentation
        run: yardoc --output-dir /tmp/docs/

      - name: save docs and publish
        run: |
          git clone https://${{ secrets.OSC_WIAG_PUB_REPO_TOKEN }}@github.com/osc/ood_core.git /tmp/core
          git config --global user.name "oscwiag"
          git config --global user.email "oscwiag@gmail.com"
          cd /tmp/core
          git checkout gh-pages
          rm -rf docs/
          mv /tmp/docs .
          git add docs/
          git commit -m 'new docs'
          git push
          
